# Generated by Django 3.1.5 on 2021-01-17 21:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20, verbose_name='Ime ekipe')),
            ],
            options={
                'verbose_name': 'Ekipa',
                'verbose_name_plural': 'Ekipe',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20, verbose_name='Sezona')),
                ('season_start', models.DateField(verbose_name='Začetek')),
                ('season_end', models.DateField(verbose_name='Konec')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('goal_per_month', models.BooleanField(default=True, verbose_name='Knjiga na mesec')),
                ('goal_per_month_nu', models.IntegerField(help_text='1', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Številko knjig na mesec')),
                ('goal_per_season', models.BooleanField(default=False, verbose_name='Številko knjig na sezono')),
                ('goal_per_season_nu', models.PositiveIntegerField(help_text='100', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Število knjig na sezono')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.team')),
            ],
            options={
                'verbose_name': 'Sezona',
                'verbose_name_plural': 'Sezone',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ime')),
                ('color', models.CharField(help_text='#3f51b5', max_length=7, verbose_name='Barva')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.team')),
            ],
            options={
                'verbose_name': 'Bralec/Bralka',
                'verbose_name_plural': 'Bralci',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Naslov knjige')),
                ('author', models.CharField(max_length=80, verbose_name='Avtor')),
                ('description', models.TextField(max_length=300, verbose_name='Opis knjige')),
                ('date_read', models.DateField(verbose_name='Datum')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.reader')),
            ],
            options={
                'verbose_name': 'Knjiga',
                'verbose_name_plural': 'Knjige',
            },
        ),
    ]
