# Generated by Django 3.1.5 on 2021-01-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ime in priimek')),
            ],
            options={
                'verbose_name': 'Bralec/Bralka',
                'verbose_name_plural': 'Bralci',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, verbose_name='Naslov knjige')),
                ('author', models.TextField(max_length=40, verbose_name='Avtor')),
                ('description', models.TextField(max_length=300, verbose_name='Opis knjige')),
                ('date_read', models.DateField(verbose_name='Datum')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.reader')),
            ],
            options={
                'verbose_name': 'Knjiga',
                'verbose_name_plural': 'Knjige',
            },
        ),
    ]
