# Generated by Django 3.1.5 on 2021-01-17 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Opis knjige'),
        ),
        migrations.AlterField(
            model_name='season',
            name='goal_per_month_nu',
            field=models.IntegerField(blank=True, help_text='1', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Številko knjig na mesec'),
        ),
        migrations.AlterField(
            model_name='season',
            name='goal_per_season_nu',
            field=models.PositiveIntegerField(blank=True, help_text='100', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Število knjig na sezono'),
        ),
    ]
