# Generated by Django 3.1.5 on 2021-01-17 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20210117_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='goal_per_month_nu',
            field=models.IntegerField(blank=True, default=0, help_text='1', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Številko knjig na mesec'),
        ),
    ]
