# Generated by Django 3.1.5 on 2021-01-17 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20210117_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='started_reading',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum začetka branja'),
            preserve_default=False,
        ),
    ]
