# Generated by Django 3.1.5 on 2021-01-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_reader_started_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='goal_per_month_nu',
            new_name='goal_per_month_no',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='goal_per_season_nu',
            new_name='goal_per_season_no',
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, help_text='298', null=True, verbose_name='Število strani'),
        ),
    ]
