# Generated by Django 3.1.5 on 2021-01-26 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20210126_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='goal_per_month_no',
            field=models.IntegerField(blank=True, default=0, help_text='1', null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Številko knjig na mesec'),
        ),
        migrations.AlterField(
            model_name='season',
            name='goal_per_season_no',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='100', null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Število knjig na sezono'),
        ),
    ]
