# Generated by Django 3.1.5 on 2021-02-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20210126_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
