# Generated by Django 3.1.5 on 2021-02-13 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0013_auto_20210213_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.team'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
