# Generated by Django 3.1.5 on 2021-02-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_auto_20210213_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.team'),
        ),
    ]
