# Generated by Django 3.1.5 on 2022-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_auto_20210213_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='full_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Polno ime'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ime na grafu'),
        ),
    ]
